language: node_js
node_js:
  - "10"
branches:
  only:
    - master
cache:
  yarn: true
script:
  - yarn && yarn copyDocToBuild && yarn deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: build
  target_branch: gh-pages
  on:
    branch: master
