# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run update
  displayName: 'npm install and update'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Pago pelo Uso (0ddc9a8c-79b9-42e5-bc09-ee677e25ff09)'
    scriptType: 'batch'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob delete-batch --source "$web" --account-name %ACCOUNT% --pattern "*" --account-key %KEY%'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Pago pelo Uso (0ddc9a8c-79b9-42e5-bc09-ee677e25ff09)'
    scriptType: 'batch'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload-batch --account-name %ACCOUNT% --source ./docs --destination "$web" --account-key %KEY%'